### ISSUE TITLE
Add "ttf-hack" to provides

### ISSUE THREAD

**Issue by evieluvsrainbows** [herecura/powerline-fonts-git#1]
When trying to run `sudo pacman -Syu` earlier today I kept running into an issue where it refused to do a system update due to a dependency breakage. Appears that `plasma-integration` needs `ttf-hack` or it doesn't end up having all of its dependencies satisfied. I was wondering if the package could be upgraded to have `ttf-hack` in provides as this package already supplies the Hack fonts.

**Comment by BlackIkeEagle** [comment]
I've added it to the provides
